sudo: false
matrix:
  allow_failures:
    - os: osx
    - python: 3.6-dev
    - env: TRAVIS_NODE_VERSION=7
  include:
    - language: python
      python: 2.7
      env: TRAVIS_NODE_VERSION=0.12
    - language: python
      python: 3.3
      env: TRAVIS_NODE_VERSION=4.5
    - language: python
      python: 3.4
      env: TRAVIS_NODE_VERSION=4.5
    - language: python
      python: 3.5
      env: TRAVIS_NODE_VERSION=6.9
    - language: python
      python: 3.6-dev
      env: TRAVIS_NODE_VERSION=7
    - language: python
      python: pypy
      env: TRAVIS_NODE_VERSION=0.12
    - language: python
      python: pypy3
      env: TRAVIS_NODE_VERSION=6.9
    # test different versions of Node.js on osx
    - language: node_js
      node_js: 4.5
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.4.5
    - language: node_js
      node_js: 6.9
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.5.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update || brew update ;
      brew install pyenv ;
      brew outdated pyenv || brew upgrade pyenv ;
      pyenv install $TRAVIS_PYTHON_VERSION ;
      pyenv global $TRAVIS_PYTHON_VERSION ;
      pyenv rehash ;
      python -m pip install --user virtualenv ;
      python -m virtualenv ~/.venv ;
      source ~/.venv/bin/activate ;
    else
      rm -rf ~/.nvm ;
      git clone https://github.com/creationix/nvm.git ~/.nvm ;
      (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` );
      source ~/.nvm/nvm.sh ;
      nvm install "$TRAVIS_NODE_VERSION" ;
    fi
  - node --version
  - npm --version

install:
  - pip install nose coverage flake8
  # must be installed first, as this writes package_json into egg-info
  - pip install -e git+https://github.com/calmjs/calmjs.git@testing#egg=calmjs
  - python setup.py develop
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      calmjs npm --install calmjs.dev -D ;
      rm -rf node_modules/karma-firefox-launcher
      export CALMJS_TEST_ENV=. ;
    fi
script:
  - flake8 setup.py src
  - nosetests --with-coverage --cover-package=calmjs.dev --with-doctest
  - coverage report -m
# Alternatively without nose
#  - coverage run --include=src/* -m unittest calmjs.dev.tests.make_suite
#  - coverage report -m
after_success:
  # only submit coverage when testing under linux.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install coveralls ;
      coveralls ;
    fi
branches:
  only:
    - testing
    - master
    - 1.0.x
