environment:
  matrix:
    - PYTHON: "C:\\Python27"
      nodejs_version: "4.5"
    - PYTHON: "C:\\Python33"
      nodejs_version: "4.5"
    - PYTHON: "C:\\Python34"
      nodejs_version: "6.5"
    - PYTHON: "C:\\Python35"
      nodejs_version: "6.9"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node $env:nodejs_version
  - pip install virtualenv
  - virtualenv --clear venv
  - "venv\\Scripts\\activate.bat"
  - pip install -e git+https://github.com/calmjs/calmjs.git@testing#egg=calmjs
  - pip install coverage
  - python setup.py install

test_script:
  - coverage run setup.py test
  - coverage report -m

artifacts:
  - path: dist\*

build: off
