environment:
  matrix:
    - PYTHON: "C:\\Python27"
      nodejs_version: "6.14"
    - PYTHON: "C:\\Python33"
      nodejs_version: "8.10"
    - PYTHON: "C:\\Python34"
      nodejs_version: "6"
    - PYTHON: "C:\\Python35"
      nodejs_version: "8"
    - PYTHON: "C:\\Python36"
      nodejs_version: "10"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node $env:nodejs_version
  - pip install virtualenv
  - virtualenv --clear venv
  - "venv\\Scripts\\activate.bat"
  - pip install coverage

  # must be installed first, as this writes package_json into egg-info
  - pip install -U calmjs
  - python setup.py develop

test_script:
  - coverage run --include=src/* -m unittest calmjs.dev.tests.make_suite
  - coverage report -m

artifacts:
  - path: dist\*

build: off
